# Generated by Django 2.1 on 2019-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('opwd', models.CharField(max_length=30)),
                ('title', models.CharField(default='添加用户的信息', max_length=50)),
            ],
            options={
                'verbose_name_plural': '添加用户和密码',
                'db_table': 'userinfo',
            },
        ),
    ]
