# Generated by Django 2.1 on 2019-01-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_addtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtime',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addtime',
            name='email2',
            field=models.EmailField(default='yang123@qq.com', max_length=50),
        ),
    ]
