# Generated by Django 2.1 on 2019-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190115_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'user'), (2, 'admin')], default=1)),
            ],
            options={
                'verbose_name_plural': '下拉框样式',
                'db_table': 'choices',
            },
        ),
    ]
