# Generated by Django 2.1 on 2019-01-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game')),
            ],
        ),
        migrations.AlterField(
            model_name='choices',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'admin'), (3, 'like')], default=1, verbose_name='下拉选择'),
        ),
    ]
